/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-05-10 20:39:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class muutavene_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\" integrity=\"sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js\"></script>\r\n");
      out.write("<title>Veneen tietojen muutos</title>\r\n");
      out.write("</head>\r\n");

int tunnus = 0;
if(request.getParameter("tunnus")!= null){
	tunnus = Integer.parseInt(request.getParameter("tunnus"));
}

String nimi = "";
if(request.getParameter("nimi") != null) {
	nimi = request.getParameter("nimi");
}

String merkkimalli = "";
if(request.getParameter("merkkimalli") != null) {
	merkkimalli = request.getParameter("merkkimalli");
}

String pituus = "";
if(request.getParameter("pituus")!= null) {
	pituus = request.getParameter("pituus");
}

String leveys = "";
if(request.getParameter("leveys")!= null) {
	leveys = request.getParameter("leveys");
}

int hinta = 0;
if(request.getParameter("hinta")!= null) {
	hinta = Integer.parseInt(request.getParameter("hinta"));
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>Veneen tietojen muuttaminen</h2>\r\n");
      out.write("\t<div class=\"lomake\">\r\n");
      out.write("\t\t<form action=\"MuutaVene\" name=\"muutaLomake\" id=\"muutaLomake\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"tunnus\" value=\"");
      out.print(tunnus);
      out.write("\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t   \t<label for=\"nimi\" class=\"col-sm-2 col-form-label\">Nimi:</label>\r\n");
      out.write("\t\t\t   \t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t    \t<input type=\"text\" class=\"form-control\" name=\"nimi\" id=nimi value=\"");
      out.print(nimi);
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  \t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t   \t<label for=\"merkkimalli\" class=\"col-sm-2 col-form-label\">Merkkimalli:</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t      \t<input type=\"text\" class=\"form-control\" name=\"merkkimalli\" id=\"merkkimalli\" value=\"");
      out.print(merkkimalli);
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  \t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t   \t<label for=\"pituus\" class=\"col-sm-2 col-form-label\">Pituus:</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t      \t<input type=\"text\" class=\"form-control\" name=\"pituus\" id=\"pituus\" value=\"");
      out.print(pituus);
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  \t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t   \t<label for=\"leveys\" class=\"col-sm-2 col-form-label\">Leveys:</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t      \t<input type=\"text\" class=\"form-control\" name=\"leveys\" id=\"leveys\" value=\"");
      out.print(leveys);
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t  \t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t   \t<label for=\"hinta\" class=\"col-sm-2 col-form-label\">Hinta:</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t      \t<input type=\"text\" class=\"form-control\" name=\"hinta\" id=\"hinta\" value=\"");
      out.print(hinta);
      out.write("\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  \t<button type=\"submit\" class=\"btn btn-primary\" value=\"lisää\">Muuta veneen tietoja</button>\r\n");
      out.write("\t\t  \t<a href=\"listaaveneet.jsp\"><button type=\"button\" class=\"btn btn-light\">Näytä kaikki veneet</button></a>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\"#muutaLomake\").validate({\r\n");
      out.write("\t\t\t\trules: {\r\n");
      out.write("\t\t\t\t\tnimi: {\r\n");
      out.write("\t\t\t\t\t\trequired: true,\r\n");
      out.write("\t\t\t\t\t\tminlength: 1,\r\n");
      out.write("\t\t\t\t\t\tmaxlength: 20\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tmerkkimalli: {\r\n");
      out.write("\t\t\t\t\t\trequired: true,\r\n");
      out.write("\t\t\t\t\t\tminlength: 1,\r\n");
      out.write("\t\t\t\t\t\tmaxlength: 20\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tpituus: {\r\n");
      out.write("\t\t\t\t\t\trequired: true,\r\n");
      out.write("\t\t\t\t\t\tnumber: true,\r\n");
      out.write("\t\t\t\t\t\tmin: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tleveys: {\r\n");
      out.write("\t\t\t\t\t\trequired: true,\r\n");
      out.write("\t\t\t\t\t\tnumber: true,\r\n");
      out.write("\t\t\t\t\t\tmin: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\thinta: {\r\n");
      out.write("\t\t\t\t\t\trequired: true,\r\n");
      out.write("\t\t\t\t\t\tnumber: true,\r\n");
      out.write("\t\t\t\t\t\tmin: 0\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tmessages: {\r\n");
      out.write("\t\t\t\t\tnimi: {\r\n");
      out.write("\t\t\t\t\t\trequired: \"Kenttä on pakollinen\",\r\n");
      out.write("\t\t\t\t\t\tminlength: \"Nimen pituus ei riitä\",\r\n");
      out.write("\t\t\t\t\t\tmaxlength: \"Nimi on liian pitkä\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tmerkkimalli: {\r\n");
      out.write("\t\t\t\t\t\trequired: \"Kenttä on pakollinen\",\r\n");
      out.write("\t\t\t\t\t\tminlength: \"Nimen pituus ei riitä\",\r\n");
      out.write("\t\t\t\t\t\tmaxlength: \"Nimi on liian pitkä\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tpituus: {\r\n");
      out.write("\t\t\t\t\t\trequired: \"Kenttä on pakollinen\",\r\n");
      out.write("\t\t\t\t\t\tnumber: \"Anna luku\",\r\n");
      out.write("\t\t\t\t\t\tmin: \"Anna positiivinen luku\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tleveys: {\r\n");
      out.write("\t\t\t\t\t\trequired: \"Kenttä on pakollinen\",\r\n");
      out.write("\t\t\t\t\t\tnumber: \"Anna luku\",\r\n");
      out.write("\t\t\t\t\t\tmin: \"Anna positiivinen luku\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\thinta: {\r\n");
      out.write("\t\t\t\t\t\trequired: \"Kenttä on pakollinen\",\r\n");
      out.write("\t\t\t\t\t\tnumber: \"Anna luku\",\r\n");
      out.write("\t\t\t\t\t\tmin: \"Anna positiivinen luku\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsubmitHandler: function (form) {\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdocument.forms[\"muutaLomake\"].submit();\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js\" integrity=\"sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js\" integrity=\"sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
